# Generated by Django 3.2.5 on 2021-11-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_iat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='tipo',
            field=models.CharField(default='normal', max_length=255),
        ),
    ]
