# Generated by Django 3.2.5 on 2021-11-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_iat', '0002_test_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ('-created_at',)},
        ),
    ]
