# Generated by Django 3.2.5 on 2021-09-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_iat', '0002_auto_20210913_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='nombre',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
