# Generated by Django 3.2.5 on 2021-11-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_iat', '0003_alter_test_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='pregunta',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultado',
            name='respuesta',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
