# Generated by Django 3.2.5 on 2021-09-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_iat', '0003_test_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tcaracteristicas',
            old_name='nombre',
            new_name='caracteristica',
        ),
        migrations.RenameField(
            model_name='tcategoria',
            old_name='nombre',
            new_name='categoria',
        ),
    ]
