# Generated by Django 3.2.5 on 2021-09-25 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_iat', '0004_auto_20210920_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tadjetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_adj', to='test_iat.adjetivo')),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adj_car', to='test_iat.tcaracteristicas')),
            ],
        ),
    ]
