# Generated by Django 3.2.5 on 2021-11-07 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_iat', '0005_auto_20211106_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sondeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondeos', to='test_iat.user')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sondeos', to='test_iat.test')),
            ],
        ),
    ]
