# Generated by Django 3.2.5 on 2021-11-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_iat', '0006_sondeo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sondeo',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('R', 'Respondido')], max_length=255),
        ),
    ]
